# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/mquinn/scheduler.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1024, 768)
        MainWindow.setMinimumSize(QtCore.QSize(1024, 768))
        MainWindow.setMaximumSize(QtCore.QSize(1024, 768))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("/home/mquinn/square.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.dropdown = QtWidgets.QComboBox(self.centralwidget)
        self.dropdown.setGeometry(QtCore.QRect(0, 0, 90, 20))
        self.dropdown.setStyleSheet("")
        self.dropdown.setObjectName("dropdown")
        self.dropdown.addItem("")
        self.dropdown.addItem("")
        self.dropdown.addItem("")
        self.search_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.search_edit.setGeometry(QtCore.QRect(110, 0, 120, 20))
        self.search_edit.setStyleSheet("")
        self.search_edit.setObjectName("search_edit")
        self.search_button = QtWidgets.QToolButton(self.centralwidget)
        self.search_button.setGeometry(QtCore.QRect(230, 0, 20, 20))
        self.search_button.setStyleSheet("background-color: rgb(0, 0, 127);")
        self.search_button.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("/home/mquinn/search.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.search_button.setIcon(icon1)
        self.search_button.setObjectName("search_button")
        self.plusbutton = QtWidgets.QPushButton(self.centralwidget)
        self.plusbutton.setGeometry(QtCore.QRect(90, 0, 20, 20))
        self.plusbutton.setStyleSheet("")
        self.plusbutton.setObjectName("plusbutton")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(260, 10, 761, 60))
        self.frame.setStyleSheet("")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.name = QtWidgets.QLabel(self.frame)
        self.name.setGeometry(QtCore.QRect(20, 20, 131, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.name.setFont(font)
        self.name.setStyleSheet("")
        self.name.setObjectName("name")
        self.id = QtWidgets.QLabel(self.frame)
        self.id.setGeometry(QtCore.QRect(150, 20, 160, 16))
        self.id.setObjectName("id")
        self.grade = QtWidgets.QLabel(self.frame)
        self.grade.setGeometry(QtCore.QRect(310, 20, 60, 16))
        self.grade.setObjectName("grade")
        self.num_credits = QtWidgets.QLabel(self.frame)
        self.num_credits.setGeometry(QtCore.QRect(375, 20, 101, 16))
        self.num_credits.setObjectName("num_credits")
        self.gpa = QtWidgets.QLabel(self.frame)
        self.gpa.setGeometry(QtCore.QRect(480, 20, 60, 16))
        self.gpa.setObjectName("gpa")
        self.name_edit = QtWidgets.QLineEdit(self.frame)
        self.name_edit.setGeometry(QtCore.QRect(75, 20, 71, 16))
        self.name_edit.setObjectName("name_edit")
        self.id_edit = QtWidgets.QLineEdit(self.frame)
        self.id_edit.setGeometry(QtCore.QRect(220, 20, 85, 16))
        self.id_edit.setObjectName("id_edit")
        self.grade_edit = QtWidgets.QLineEdit(self.frame)
        self.grade_edit.setGeometry(QtCore.QRect(355, 20, 16, 16))
        self.grade_edit.setObjectName("grade_edit")
        self.credits_edit = QtWidgets.QLineEdit(self.frame)
        self.credits_edit.setGeometry(QtCore.QRect(460, 20, 16, 16))
        self.credits_edit.setObjectName("credits_edit")
        self.gpa_edit = QtWidgets.QLineEdit(self.frame)
        self.gpa_edit.setGeometry(QtCore.QRect(510, 20, 32, 16))
        self.gpa_edit.setObjectName("gpa_edit")
        self.edit_button = QtWidgets.QToolButton(self.frame)
        self.edit_button.setGeometry(QtCore.QRect(740, 40, 20, 20))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("/home/mquinn/edit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.edit_button.setIcon(icon2)
        self.edit_button.setObjectName("edit_button")
        self.name_search = QtWidgets.QPushButton(self.centralwidget)
        self.name_search.setGeometry(QtCore.QRect(0, 20, 125, 23))
        font = QtGui.QFont()
        font.setKerning(True)
        self.name_search.setFont(font)
        self.name_search.setStyleSheet("")
        self.name_search.setObjectName("name_search")
        self.ID_search = QtWidgets.QPushButton(self.centralwidget)
        self.ID_search.setGeometry(QtCore.QRect(125, 20, 125, 23))
        self.ID_search.setStyleSheet("")
        self.ID_search.setObjectName("ID_search")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(0, 40, 250, 681))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 248, 679))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalScrollBar = QtWidgets.QScrollBar(self.scrollAreaWidgetContents)
        self.verticalScrollBar.setGeometry(QtCore.QRect(230, 0, 21, 521))
        self.verticalScrollBar.setOrientation(QtCore.Qt.Vertical)
        self.verticalScrollBar.setObjectName("verticalScrollBar")
        self.logo = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.logo.setGeometry(QtCore.QRect(0, 640, 121, 41))
        self.logo.setText("")
        self.logo.setPixmap(QtGui.QPixmap("/home/mquinn/Webp.net-resizeimage.png"))
        self.logo.setObjectName("logo")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(260, 80, 372, 275))
        self.frame_2.setStyleSheet("")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.preferences = QtWidgets.QLabel(self.frame_2)
        self.preferences.setGeometry(QtCore.QRect(20, 20, 241, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.preferences.setFont(font)
        self.preferences.setStyleSheet("")
        self.preferences.setObjectName("preferences")
        self.preference1 = QtWidgets.QLabel(self.frame_2)
        self.preference1.setGeometry(QtCore.QRect(20, 56, 225, 15))
        self.preference1.setObjectName("preference1")
        self.preference2 = QtWidgets.QLabel(self.frame_2)
        self.preference2.setGeometry(QtCore.QRect(20, 86, 225, 15))
        self.preference2.setObjectName("preference2")
        self.preference3 = QtWidgets.QLabel(self.frame_2)
        self.preference3.setGeometry(QtCore.QRect(20, 116, 225, 15))
        self.preference3.setObjectName("preference3")
        self.preference4 = QtWidgets.QLabel(self.frame_2)
        self.preference4.setGeometry(QtCore.QRect(20, 146, 225, 15))
        self.preference4.setObjectName("preference4")
        self.preference5 = QtWidgets.QLabel(self.frame_2)
        self.preference5.setGeometry(QtCore.QRect(20, 176, 225, 15))
        self.preference5.setObjectName("preference5")
        self.preference6 = QtWidgets.QLabel(self.frame_2)
        self.preference6.setGeometry(QtCore.QRect(20, 206, 225, 15))
        self.preference6.setObjectName("preference6")
        self.pref1edit = QtWidgets.QLineEdit(self.frame_2)
        self.pref1edit.setGeometry(QtCore.QRect(40, 56, 211, 16))
        self.pref1edit.setObjectName("pref1edit")
        self.pref2edit = QtWidgets.QLineEdit(self.frame_2)
        self.pref2edit.setGeometry(QtCore.QRect(40, 86, 211, 16))
        self.pref2edit.setObjectName("pref2edit")
        self.pref3edit = QtWidgets.QLineEdit(self.frame_2)
        self.pref3edit.setGeometry(QtCore.QRect(40, 116, 211, 16))
        self.pref3edit.setObjectName("pref3edit")
        self.pref4edit = QtWidgets.QLineEdit(self.frame_2)
        self.pref4edit.setGeometry(QtCore.QRect(40, 146, 211, 16))
        self.pref4edit.setObjectName("pref4edit")
        self.pref5edit = QtWidgets.QLineEdit(self.frame_2)
        self.pref5edit.setGeometry(QtCore.QRect(40, 176, 211, 16))
        self.pref5edit.setObjectName("pref5edit")
        self.pref6edit = QtWidgets.QLineEdit(self.frame_2)
        self.pref6edit.setGeometry(QtCore.QRect(40, 206, 211, 16))
        self.pref6edit.setObjectName("pref6edit")
        self.preference6_2 = QtWidgets.QLabel(self.frame_2)
        self.preference6_2.setGeometry(QtCore.QRect(20, 236, 225, 15))
        self.preference6_2.setObjectName("preference6_2")
        self.pref7edit = QtWidgets.QLineEdit(self.frame_2)
        self.pref7edit.setGeometry(QtCore.QRect(40, 236, 211, 16))
        self.pref7edit.setObjectName("pref7edit")
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setGeometry(QtCore.QRect(642, 80, 372, 275))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.requirements_scroll = QtWidgets.QScrollArea(self.frame_3)
        self.requirements_scroll.setGeometry(QtCore.QRect(0, 0, 372, 275))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.requirements_scroll.sizePolicy().hasHeightForWidth())
        self.requirements_scroll.setSizePolicy(sizePolicy)
        self.requirements_scroll.setMinimumSize(QtCore.QSize(0, 100))
        self.requirements_scroll.setStyleSheet("\n"
"")
        self.requirements_scroll.setWidgetResizable(True)
        self.requirements_scroll.setObjectName("requirements_scroll")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 356, 942))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.requirements = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.requirements.setFont(font)
        self.requirements.setObjectName("requirements")
        self.verticalLayout.addWidget(self.requirements)
        self.label_fsa = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_fsa.setObjectName("label_fsa")
        self.verticalLayout.addWidget(self.label_fsa)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.checkBox_fsa_ela = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_2)
        self.checkBox_fsa_ela.setObjectName("checkBox_fsa_ela")
        self.verticalLayout_2.addWidget(self.checkBox_fsa_ela)
        self.checkBox_fsa_algebra = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_2)
        self.checkBox_fsa_algebra.setObjectName("checkBox_fsa_algebra")
        self.verticalLayout_2.addWidget(self.checkBox_fsa_algebra)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        self.label_ela = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_ela.setObjectName("label_ela")
        self.verticalLayout.addWidget(self.label_ela)
        self.checkBox_ela_1 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_2)
        self.checkBox_ela_1.setObjectName("checkBox_ela_1")
        self.verticalLayout.addWidget(self.checkBox_ela_1)
        self.checkBox_ela_2 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_2)
        self.checkBox_ela_2.setObjectName("checkBox_ela_2")
        self.verticalLayout.addWidget(self.checkBox_ela_2)
        self.checkBox_ela_3 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_2)
        self.checkBox_ela_3.setObjectName("checkBox_ela_3")
        self.verticalLayout.addWidget(self.checkBox_ela_3)
        self.checkBox_ela_4 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_2)
        self.checkBox_ela_4.setObjectName("checkBox_ela_4")
        self.verticalLayout.addWidget(self.checkBox_ela_4)
        self.label_math = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_math.setObjectName("label_math")
        self.verticalLayout.addWidget(self.label_math)
        self.checkBox_algebra = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_2)
        self.checkBox_algebra.setObjectName("checkBox_algebra")
        self.verticalLayout.addWidget(self.checkBox_algebra)
        self.checkBox_geometry = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_2)
        self.checkBox_geometry.setObjectName("checkBox_geometry")
        self.verticalLayout.addWidget(self.checkBox_geometry)
        self.checkBox_math_3 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_2)
        self.checkBox_math_3.setObjectName("checkBox_math_3")
        self.verticalLayout.addWidget(self.checkBox_math_3)
        self.checkBox_math_4 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_2)
        self.checkBox_math_4.setObjectName("checkBox_math_4")
        self.verticalLayout.addWidget(self.checkBox_math_4)
        self.label_science = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_science.setObjectName("label_science")
        self.verticalLayout.addWidget(self.label_science)
        self.checkBox_bio = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_2)
        self.checkBox_bio.setObjectName("checkBox_bio")
        self.verticalLayout.addWidget(self.checkBox_bio)
        self.checkBox_sci_2 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_2)
        self.checkBox_sci_2.setObjectName("checkBox_sci_2")
        self.verticalLayout.addWidget(self.checkBox_sci_2)
        self.checkBox_sci_3 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_2)
        self.checkBox_sci_3.setObjectName("checkBox_sci_3")
        self.verticalLayout.addWidget(self.checkBox_sci_3)
        self.label_social_studies = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_social_studies.setObjectName("label_social_studies")
        self.verticalLayout.addWidget(self.label_social_studies)
        self.checkBox_history_us = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_2)
        self.checkBox_history_us.setObjectName("checkBox_history_us")
        self.verticalLayout.addWidget(self.checkBox_history_us)
        self.checkBox_history_world = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_2)
        self.checkBox_history_world.setObjectName("checkBox_history_world")
        self.verticalLayout.addWidget(self.checkBox_history_world)
        self.checkBox_gov = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_2)
        self.checkBox_gov.setObjectName("checkBox_gov")
        self.verticalLayout.addWidget(self.checkBox_gov)
        self.checkBox_econ = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_2)
        self.checkBox_econ.setObjectName("checkBox_econ")
        self.verticalLayout.addWidget(self.checkBox_econ)
        self.label_electives = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_electives.setObjectName("label_electives")
        self.verticalLayout.addWidget(self.label_electives)
        self.checkBox_e1 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_2)
        self.checkBox_e1.setObjectName("checkBox_e1")
        self.verticalLayout.addWidget(self.checkBox_e1)
        self.checkBox_e2 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_2)
        self.checkBox_e2.setObjectName("checkBox_e2")
        self.verticalLayout.addWidget(self.checkBox_e2)
        self.checkBox_e3 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_2)
        self.checkBox_e3.setObjectName("checkBox_e3")
        self.verticalLayout.addWidget(self.checkBox_e3)
        self.checkBox_e4 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_2)
        self.checkBox_e4.setObjectName("checkBox_e4")
        self.verticalLayout.addWidget(self.checkBox_e4)
        self.checkBox_e5 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_2)
        self.checkBox_e5.setObjectName("checkBox_e5")
        self.verticalLayout.addWidget(self.checkBox_e5)
        self.checkBox_e6 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_2)
        self.checkBox_e6.setObjectName("checkBox_e6")
        self.verticalLayout.addWidget(self.checkBox_e6)
        self.checkBox_e7 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_2)
        self.checkBox_e7.setObjectName("checkBox_e7")
        self.verticalLayout.addWidget(self.checkBox_e7)
        self.checkBox_e8 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_2)
        self.checkBox_e8.setObjectName("checkBox_e8")
        self.verticalLayout.addWidget(self.checkBox_e8)
        self.label_other = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_other.setObjectName("label_other")
        self.verticalLayout.addWidget(self.label_other)
        self.checkBox_art = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_2)
        self.checkBox_art.setObjectName("checkBox_art")
        self.verticalLayout.addWidget(self.checkBox_art)
        self.checkBox_pe = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_2)
        self.checkBox_pe.setObjectName("checkBox_pe")
        self.verticalLayout.addWidget(self.checkBox_pe)
        self.checkBox_online = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_2)
        self.checkBox_online.setObjectName("checkBox_online")
        self.verticalLayout.addWidget(self.checkBox_online)
        self.requirements_scroll.setWidget(self.scrollAreaWidgetContents_2)
        self.frame_4 = QtWidgets.QFrame(self.centralwidget)
        self.frame_4.setGeometry(QtCore.QRect(260, 365, 751, 355))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.label = QtWidgets.QLabel(self.frame_4)
        self.label.setGeometry(QtCore.QRect(20, 20, 131, 16))
        self.label.setObjectName("label")
        self.tableWidget = QtWidgets.QTableWidget(self.frame_4)
        self.tableWidget.setGeometry(QtCore.QRect(20, 56, 320, 131))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget.sizePolicy().hasHeightForWidth())
        self.tableWidget.setSizePolicy(sizePolicy)
        self.tableWidget.setStyleSheet("")
        self.tableWidget.setCornerButtonEnabled(True)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setRowCount(6)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 2, item)
        self.ok_button = QtWidgets.QPushButton(self.frame_4)
        self.ok_button.setGeometry(QtCore.QRect(661, 322, 80, 23))
        self.ok_button.setStyleSheet("")
        self.ok_button.setObjectName("ok_button")
        self.frame_3.raise_()
        self.dropdown.raise_()
        self.search_edit.raise_()
        self.search_button.raise_()
        self.plusbutton.raise_()
        self.frame.raise_()
        self.name_search.raise_()
        self.ID_search.raise_()
        self.scrollArea.raise_()
        self.frame_2.raise_()
        self.frame_4.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1024, 20))
        self.menubar.setObjectName("menubar")
        self.menutoolbar = QtWidgets.QMenu(self.menubar)
        self.menutoolbar.setObjectName("menutoolbar")
        self.menuImport_Students = QtWidgets.QMenu(self.menutoolbar)
        self.menuImport_Students.setObjectName("menuImport_Students")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionImport_Teachers = QtWidgets.QAction(MainWindow)
        self.actionImport_Teachers.setObjectName("actionImport_Teachers")
        self.actionStudents = QtWidgets.QAction(MainWindow)
        self.actionStudents.setObjectName("actionStudents")
        self.actionTeachers = QtWidgets.QAction(MainWindow)
        self.actionTeachers.setObjectName("actionTeachers")
        self.actionCourses = QtWidgets.QAction(MainWindow)
        self.actionCourses.setObjectName("actionCourses")
        self.actionSettings = QtWidgets.QAction(MainWindow)
        self.actionSettings.setObjectName("actionSettings")
        self.menuImport_Students.addAction(self.actionStudents)
        self.menuImport_Students.addSeparator()
        self.menuImport_Students.addAction(self.actionTeachers)
        self.menuImport_Students.addSeparator()
        self.menuImport_Students.addAction(self.actionCourses)
        self.menuImport_Students.addSeparator()
        self.menutoolbar.addAction(self.menuImport_Students.menuAction())
        self.menutoolbar.addAction(self.actionImport_Teachers)
        self.menutoolbar.addAction(self.actionSettings)
        self.menubar.addAction(self.menutoolbar.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.dropdown.setItemText(0, _translate("MainWindow", "Students"))
        self.dropdown.setItemText(1, _translate("MainWindow", "Teachers"))
        self.dropdown.setItemText(2, _translate("MainWindow", "Courses"))
        self.plusbutton.setText(_translate("MainWindow", "+"))
        self.name.setText(_translate("MainWindow", "Name:"))
        self.id.setText(_translate("MainWindow", "Student ID:"))
        self.grade.setText(_translate("MainWindow", "Grade: "))
        self.num_credits.setText(_translate("MainWindow", "Total Credits: "))
        self.gpa.setText(_translate("MainWindow", "GPA: "))
        self.edit_button.setText(_translate("MainWindow", "..."))
        self.name_search.setText(_translate("MainWindow", "Name                      "))
        self.ID_search.setText(_translate("MainWindow", "ID                           "))
        self.preferences.setText(_translate("MainWindow", "Course Preferences"))
        self.preference1.setText(_translate("MainWindow", "1. "))
        self.preference2.setText(_translate("MainWindow", "2. "))
        self.preference3.setText(_translate("MainWindow", "3. "))
        self.preference4.setText(_translate("MainWindow", "4. "))
        self.preference5.setText(_translate("MainWindow", "5. "))
        self.preference6.setText(_translate("MainWindow", "6. "))
        self.preference6_2.setText(_translate("MainWindow", "7. "))
        self.requirements.setText(_translate("MainWindow", "Graduation Requirements"))
        self.label_fsa.setText(_translate("MainWindow", "State Assessments"))
        self.checkBox_fsa_ela.setText(_translate("MainWindow", "FSA ELA"))
        self.checkBox_fsa_algebra.setText(_translate("MainWindow", "FSA Algebra 1 EOC"))
        self.label_ela.setText(_translate("MainWindow", "ELA"))
        self.checkBox_ela_1.setText(_translate("MainWindow", "English 1"))
        self.checkBox_ela_2.setText(_translate("MainWindow", "English 2"))
        self.checkBox_ela_3.setText(_translate("MainWindow", "English 3"))
        self.checkBox_ela_4.setText(_translate("MainWindow", "English 4"))
        self.label_math.setText(_translate("MainWindow", "Mathematics"))
        self.checkBox_algebra.setText(_translate("MainWindow", "Algebra 1"))
        self.checkBox_geometry.setText(_translate("MainWindow", "Geometry"))
        self.checkBox_math_3.setText(_translate("MainWindow", "Mathematrics 3rd Credit"))
        self.checkBox_math_4.setText(_translate("MainWindow", "Mathematics 4th Credit"))
        self.label_science.setText(_translate("MainWindow", "Science"))
        self.checkBox_bio.setText(_translate("MainWindow", "Biology"))
        self.checkBox_sci_2.setText(_translate("MainWindow", "Science 2nd Credit"))
        self.checkBox_sci_3.setText(_translate("MainWindow", "Science 3rd Credit"))
        self.label_social_studies.setText(_translate("MainWindow", "Social Studies"))
        self.checkBox_history_us.setText(_translate("MainWindow", "U.S. History"))
        self.checkBox_history_world.setText(_translate("MainWindow", "World History"))
        self.checkBox_gov.setText(_translate("MainWindow", "U.S. Government"))
        self.checkBox_econ.setText(_translate("MainWindow", "Economics"))
        self.label_electives.setText(_translate("MainWindow", "Electives"))
        self.checkBox_e1.setText(_translate("MainWindow", "Elective 1"))
        self.checkBox_e2.setText(_translate("MainWindow", "Elective 2"))
        self.checkBox_e3.setText(_translate("MainWindow", "Elective 3"))
        self.checkBox_e4.setText(_translate("MainWindow", "Elective 4"))
        self.checkBox_e5.setText(_translate("MainWindow", "Elective 5"))
        self.checkBox_e6.setText(_translate("MainWindow", "Elective 6"))
        self.checkBox_e7.setText(_translate("MainWindow", "Elective 7"))
        self.checkBox_e8.setText(_translate("MainWindow", "Elective 8"))
        self.label_other.setText(_translate("MainWindow", "Other"))
        self.checkBox_art.setText(_translate("MainWindow", "Fine and Performing Arts"))
        self.checkBox_pe.setText(_translate("MainWindow", "Physical Education"))
        self.checkBox_online.setText(_translate("MainWindow", "Online "))
        self.label.setText(_translate("MainWindow", "Past Coursework"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Name"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Credits"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Grade"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.item(0, 0)
        item.setText(_translate("MainWindow", "Algebra 1"))
        item = self.tableWidget.item(0, 1)
        item.setText(_translate("MainWindow", "1"))
        item = self.tableWidget.item(0, 2)
        item.setText(_translate("MainWindow", "A"))
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.ok_button.setText(_translate("MainWindow", "Ok"))
        self.menutoolbar.setTitle(_translate("MainWindow", "File"))
        self.menuImport_Students.setTitle(_translate("MainWindow", "Import Students"))
        self.actionImport_Teachers.setText(_translate("MainWindow", "Export Schedules"))
        self.actionStudents.setText(_translate("MainWindow", "Students"))
        self.actionTeachers.setText(_translate("MainWindow", "Teachers"))
        self.actionCourses.setText(_translate("MainWindow", "Courses"))
        self.actionSettings.setText(_translate("MainWindow", "Settings"))
